### ISSUE TITLE
Documentation Request: Guide for Adding Multiple Validators to a Network

### ISSUE THREAD

**Issue by shivhg** [rollchains/spawn#102]
Hello,

I successfully initiated a blockchain network with a single validator following the steps below, but I'm encountering difficulties when trying to expand the network with multiple validators. Could detailed instructions for adding multiple validators be included in the documentation? Here's the successful procedure for a single validator:

1. Generate keys for the validator: `rolld keys add fastbraze`
2. Initialize the node with a specific chain ID: `rolld init unmar_beta0 --chain-id=44`
3. Add the genesis account with a substantial stake: `rolld genesis add-genesis-account <fastbraze-address> 1000000000000stake`
4. Generate a genesis transaction (gentx) for the validator: `rolld genesis gentx fastbraze 1000000000000stake --chain-id=44`
5. Collect the genesis transactions: `rolld genesis collect-gentxs`
6. Start the network: `rolld start`

This process successfully launches a network with one validator. However, when attempting to replicate this process or modify it for adding additional validators, I run into issues, especially around the gentx step for subsequent validators, with errors indicating problems generating or recognizing gentx files properly.

For clarity and the benefit of the community, could the documentation be enhanced to include a step-by-step guide on expanding a network by adding multiple validators? Such guidance would be invaluable for those of us looking to build more complex and robust networks.

Thank you for considering this request.

**Comment by reecepbcups** [comment]
@shivhg Have you tried using the local-ic setup, we have support for this there

check the chains/ibc-testnet.json file, and you can change `number_vals` to be >1./ Keep number_node at 0 (no need for full nodes here)

then `make testnet`

we should make this more clear

**Comment by shivhg** [comment]
Thanks for the guidance on setting up the IBC testnet, @Reecepbcups. I noticed that the process automatically generates validator credentials. For our specific use case, we need to initialize the network with pre-defined validator credentials, similar to how we can specify initial account addresses.

Could you provide guidance or point me to documentation on how to modify the testnet setup process to accept a file containing validator credentials (public/private keys, addresses)? Ideally, this file would be similar to the one used for specifying initial account addresses, allowing us to maintain a consistent setup across different environments.

**Comment by reecepbcups** [comment]
@shivhg This feature req would have to be made upstream @ https://github.com/strangelove-ventures/interchaintest

The `andrew/start_with_genesis` has a portion of this, but to change the pub/priv ed25519 consensus signing keys would require some work.

This seems odd though that it has to be deterministic? The setup allows you to control the validator created with each testnet via the `--from=validator --keyring-backend=test` for execution and queries

**Comment by shivhg** [comment]
@Reecepbcups One more question, Any blogs or references to deploying the testnet to the cloud? I see you have this in video walkthrough yet to be done

**Comment by reecepbcups** [comment]
I am working on this right now! - latest PR is almost done - https://github.com/rollchains/spawn/pull/105

**Comment by reecepbcups** [comment]
@shivhg This workflow is now found within the simapp/. A future release will include this by default, but you can copy paste for now

https://github.com/rollchains/spawn/blob/release/v0.50/simapp/.github/workflows/hetzner-cloud-testnet.yml

it requires this file for the format: https://github.com/rollchains/spawn/blob/release/v0.50/simapp/.github/testnet.md

**Comment by reecepbcups** [comment]
since this is more of a local-ic / interchaintest PR, going to close here until that upstream change takes place for this feature
