### ISSUE TITLE
feat: Ethos onboarding

### ISSUE THREAD

**Issue by reecepbcups** [rollchains/spawn#127]
## New Chains
- Ethos feature toggle
  - ICS, Contracts, ICTest, Unit?

## Existing
- Write an internal spawn plugin to add Ethos to an existing standard cosmos simapp codebase

**Comment by reecepbcups** [comment]
ref: initial base ICS #112

**Comment by jonathanpberger** [comment]
Waiting on upstream integration test fixes from the Ethos team.

**Comment by reecepbcups** [comment]
closed as upstream ethos team has pivoted to InfiniteVM. Main repo has not had real work in a considerable time.

Closing as upstream stale.
