### ISSUE TITLE
Hyphen in org name generates invalid .proto files

### ISSUE THREAD

**Issue by mvid** [rollchains/spawn#138]
Setting `--org=name-with-hyphen` results in an invalid package path in proto files, as hyphen's are not valid in names

**Comment by reecepbcups** [comment]
good catch, I’ll replace with _ for proto namespaces or remove entirely from the namespace for new modules

**Comment by reecepbcups** [comment]
Removed entirely as its not actually required for the proto module v1. Build latest spawn and creating new modules will work as expected

for any  current module proto, just remove the `my-org.myproject.` in the proto/module/v1 dir
