### ISSUE TITLE
Eigenlayer AVSs

### ISSUE THREAD

**Issue by reecepbcups** [rollchains/spawn#169]
## Goal
Make it super easy to launch and test an [Eigenlayer](https://twitter.com/eigenlayer) secured AVS <-> Cosmos
- Share security (permissionless PoS with ueth)
- Grab other values from the AVS whjich an operator has verified

## Base
https://github.com/Layr-Labs/awesome-avs

## References
- https://github.com/Layr-Labs/hello-world-avs/
- https://github.com/Layr-Labs/incredible-squaring-avs (off chain oracle that squares numbers)
- https://github.com/hack3r-0m/cosmoavs (lol What?)

**Comment by reecepbcups** [comment]
## Notes
```
Layr-Labs/hello-world-avs

sudo pacman -S yarn typescript

curl -L https://foundry.paradigm.xyz | bash
source it in the bash (.foundry/bin)

make start-chain-with-contracts-deployed

make start-operator
```

**Comment by reecepbcups** [comment]
# Cosmos AVS

easy launch AVS (git sub-module?)
Cosmos PoS chain
anyone can create a validator with 1TOKEN (min delegation)
VE++ -> the AVS
Binding -> Cosmos to ETH 0x (include a msg signature to verify on the cosmos side)
Pull and update delegators based on this

Distribution: Send rewards to shareholders which are 1-1 interacted for on the eth side
default: save just 0x on other side (no cosmos withdraw)
They will submit tx in the future to link their cosmos to an eth + msg signature

**Comment by Reecepbcups** [comment]
Spawn should focus on eth x cosmwasm / cosmos, vs connecting to ETH.
