### ISSUE TITLE
fix(docs): WSL error with golang mod cache in general

### ISSUE THREAD

**Issue by reecepbcups** [rollchains/spawn#226]
Ref 1 (Aug 2024): https://discord.com/channels/669268347736686612/1275514566104584202/1275514566104584202
Ref 2 (Oct 1, 2024): https://discord.com/channels/669268347736686612/1290674907134558229

2 users now have reported this issue where WSL likes to mess with the go instance cache for some reason. This is not related to spawn directly, but rather indirect due to the SDK/Go being used.

`make protoc-gen`

```
github.com/rollchains/rollchain/api/nameservice/module/v1: cannot find module providing package github.com/rollchains/rollchain/api/nameservice/module/v1: module github.com/rollchains/rollchain/api/nameservice/module: git ls-remote -q origin in /root/go/pkg/mod/cache/vcs/5c185abe3132c155eb28cff6824b74990ed6a2add5f97b0869c7e09afad95925: exit status 128:
        Host key verification failed.
        fatal: Could not read from remote repository.
```

## ref 1
![Image](https://github.com/user-attachments/assets/3e9d5323-ca7c-4188-85b4-0c257a54fb96)
![Image](https://github.com/user-attachments/assets/ca77e5c8-7531-4385-9458-65a3713f67d9)

attempts go1.23.0
![Image](https://github.com/user-attachments/assets/a61e16d3-e181-44ee-b990-fa0700256130)

![Image](https://github.com/user-attachments/assets/6dbc30db-9287-47d7-af04-4ad6e46cc1ad)

reinstalls WSL and sets up properly using spawn docs

"Thank you very much! I cleaned the go cache and after that moved to the myproject directory and then"
![Image](https://github.com/user-attachments/assets/3f936fc7-75ac-4ce6-8f4e-1473f22c49b9)

## Ref 2
![Image](https://github.com/user-attachments/assets/d3271dc4-6e64-4d09-83eb-ba34d2630eba)
![Image](https://github.com/user-attachments/assets/9367151c-1bf5-40ef-b14c-bef787e2d581)

## Solution
```
go clean -modcache 
# or rm -rf $HOME/go/pkg/mod
make protoc-gen
```

**Comment by reecepbcups** [comment]
Resolved in https://github.com/rollchains/spawn/commit/7d8f1fd864114a7fcb6309ad473337a1b57bbea0

Another user in the discord now with the same issues but apperently the clean and make proto-gen does not work for them. They previously did not have their go env setup properly. Assume it is still something on their end & not ours given the circumstances

**Comment by RobertoFacilita** [comment]
![Image](https://github.com/user-attachments/assets/e713a3c0-6233-4c83-adaf-609b50628269)

I cleaned the mod, an run the command to dowload dependencies again

but i receive this error:
![Image](https://github.com/user-attachments/assets/27fe8547-cbed-4b12-9867-7bd3488ce059)

these are my go envs:
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/roberto/.cache/go-build'
GOENV='/home/roberto/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/roberto/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/roberto/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/usr/local/go'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/usr/local/go/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.23.0'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/roberto/.config/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/home/roberto/Documents/PersonalProjects/spawn/rollchain/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build3251093546=/tmp/go-build -gno-record-gcc-switches'
