### ISSUE TITLE
cargo install cargo generate in the docs

### ISSUE THREAD

**Issue by reecepbcups** [rollchains/spawn#249]

**Comment by olliegilbey** [comment]
same for cargo-run-script
needs to be cargo installed first

**Comment by olliegilbey** [comment]
zoxide: no match found

(different issue) spawn new chain

**Comment by olliegilbey** [comment]
spawn new cwchain \
--consensus=proof-of-stake \
--bech32=roll \
--denom=uroll \
--bin=rolld \
--disabled=block-explorer \
--org=${GITHUB_USERNAME}
[1]    48283 killed     spawn new cwchain --consensus=proof-of-stake --bech32=roll --denom=uroll

**Comment by olliegilbey** [comment]
With a clean spawn clone as well:

spawn new rollchain --consensus=pos --disable=cosmwasm --bech32=roll --denom=uroll --bin=rolld
[1]    55659 killed     spawn new rollchain --consensus=pos --disable=cosmwasm --bech32=roll
