### ISSUE TITLE
TX error on local testnet using ICS

### ISSUE THREAD

**Issue by rattadan** [rollchains/spawn#267]
Hey, using the sh-testnet works fine for POS mode, but using ICS mode, a tx returns error:

auth_info:
  fee:
    amount: []
    gas_limit: "200000"
    granter: ""
    payer: ""
  signer_infos: []
  tip: null
body:
  extension_options: []
  memo: ""
  messages:
  - '@type': /cosmos.bank.v1beta1.MsgSend
    amount:
    - amount: "100"
      denom: roll
    from_address: roll1hj5fveer5cjtn4wd6wstzugjfdxzl0xpg2te87
    to_address: roll1efd63aw40lxf3n4mhf7dzhjkr453axur57cawh
  non_critical_extension_options: []
  timeout_height: "0"
signatures: []
confirm transaction before signing and broadcasting [y/N]: y
code: 1
codespace: undefined
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: tx contains unsupported message types at height 20
timestamp: ""
tx: null
txhash: 576B93DF4C9EC89577095F28F81126D28D5A0E37C84BDE7828D72D5FC8D33DAE

raw_log: tx contains unsupported message types at height 20

this is repeatable on other systems too,...

**Comment by Reecepbcups** [comment]
make sh-testet is a hack for quick development. it does not use IBC so ICS staking won’t work

to use ics staking you must use the make testnet command with docker. This spins up a hub provider, the consumer, and the relayer

**Comment by rattadan** [comment]
Thanks a lot for that fast response... 

Reece:
make sh-testet is a hack for quick development. it does not use IBC so ICS staking won’t work

to use ics staking you must use the make testnet command with docker. This spins up a hub provider, the consumer, and the relayer
