### ISSUE TITLE
Testnet support

### ISSUE THREAD

**Issue by jackzampolin** [rollchains/spawn#62]
Think about what a deploy testnet GitHub action might look like and what it would do.

**Comment by reecepbcups** [comment]
Self hosted runner? requires mounting. Make it its own action behind a SL API? needs to be restartable w/ mounting. production-ize the local-ic. Public vs Private repos are going to be a pain ? (remote config should help this to use ghcr instead)

## Hetzner
- [x]  Hetzner

## Self Hosted
- [x] done

## Future
- GCP
- Akash

**Comment by reecepbcups** [comment]
ref #105 (public, hetzner cloud) and #107 (private self hosted, which can still use hetzner) both done.

Closing
