### ISSUE TITLE
validate: chain creation & modules

### ISSUE THREAD

**Issue by Reecepbcups** [rollchains/spawn#86]
Unsure what gh can handle. Manual process for releases is most scaleable. Biggest pitfalls should be in internal CI? (unless we can fit all then cool)

- [x] Add ICTest test on base chain (just Basic to ensure it runs?)

# Update v0.50.* in the README to the new tag name before tagging!

# make sure README works as expected manually (i.e. clear wallet keys, etc)

# Approach 0 - Manual Checks Privately
Should write a script / document for this. May be the best solution for now (do off the branch before tagging)

```bash
# run the cmd, and in vscode press publish branch (auto creates private/public repo for you).
# maybe also run a go test / docker build here?

# standard
spawn new base --bypass-prompt --bech32=abcd --bin=aaaaad --denom=uxyz --org=strangelove && code base/

# nothing at all, just cosmos
spawn new minimal --disable=proof-of-authority,tokenfactory,globalfee,ibc-packetforward,cosmwasm,ignite,wasm-light-client --bech32=abcd --bin=aaaaad --denom=uxyz --org=strangelove && code minimal/

# only cosmwasm
spawn new mycw --disable=tokenfactory,poa,globalfee,ibc-packetforward --bech32=abcd --bin=aaaaad --denom=uxyz --org=reecepbcups && code mycw/

# wasmlc no wasm
spawn new mywlc --disable=tokenfactory,poa,globalfee,ibc-packetforward,cosmwasm && code mywlc/

# TODO: ibc-ratelimit, ics

# mixes
spawn new randmix --disable=globalfee,wasmlc,ignite && cd randmix && go test ./... && cd .. && rm -rf randmix/
spawn new randmix --disable=wasmlc,tokenfactory && cd randmix && go test ./... && cd .. && rm -rf randmix/
spawn new randmix --disable=wasmlc,wasm && cd randmix && go test ./... && cd .. && rm -rf randmix/
spawn new randmix --disable=poa,globalfee && cd randmix && go test ./... && cd .. && rm -rf randmix/
spawn new randmix --disable=poa,globalfee && cd randmix && go test ./... && cd .. && rm -rf randmix/
spawn new randmix --disable=tokenfactory,poa,packetforward && cd randmix && go test ./... && cd .. && rm -rf randmix/
spawn new randmix --disable=packetforward,cosmwasm,ignite,ignite && cd randmix && go test ./... && cd .. && rm -rf randmix/
spawn new randmix --disable=cosmwasm,cosmwasm,wasm-light-client && cd randmix && go test ./... && cd .. && rm -rf randmix/

# validate ictest testnets with base install, and one with all (make testnet)
```

## Approach 1
Chain 1:
- defaults, no changes. just change binary, org, token, & wallet prefix
- go test
- validate the chain starts with `make sh-testnet` ? (in the backrgound)
- make local-image
- seperate threads, run make ictest-basic, ictest-poa

Chain2: (opposite of what is the default). Keep all default flags
- Yes: `Wasm, Light Client, IgniteCLI`. No: `GlobalFee, TokenFactory, PoA`
- go test
- make local-image
- make ictest-basic, ictest-wasm

# Approach 2
- Randomize matrixes

## Approach 3
- Gen all matrix permutations (disabled and enabled), then just go test ./…

**Comment by Reecepbcups** [comment]
should really make a doc for future integrations too. showcase exact steps to test

also add new module generation (maybe do that in this repos CI automatically, then go test)

**Comment by reecepbcups** [comment]
https://github.com/rollchains/spawn/pull/133

**Comment by Reecepbcups** [comment]
- [ ] Add to checklist for checking generation CI w/ ICS feature matrix (i.e. keeping POA w/ ICS, etc). See what I can spawn unit test

multi-chain creation validation (mass matrix, ensure it go test / source is valid parsed w/ go std lib). Feeling the std lib route for CI, but

Will still require the github new repo pushes for now. Would be nice to have a gh CLI cmd to delete those repos quickly

**Comment by Reecepbcups** [comment]
Run other commands after new chain, before unit test (i.e. add module)
 
 tried to do in current spawn-e2e in the middle and it did not like the make proto-gen creation. So needs to be its own UI

**Comment by Reecepbcups** [comment]
Add docs guide .md with info on running the matrix and how to perform an upgrade. That way this can be deleted

**Comment by Reecepbcups** [comment]
modules is being handled in #143, but we should also write in custom proto & verify it moves properly etc

**Comment by reecepbcups** [comment]
https://github.com/rollchains/spawn/pull/143#discussion_r1619583860

**Comment by Reecepbcups** [comment]
update get-localic make file (or auto pull latest based on IBC version)

**Comment by reecepbcups** [comment]
simulte cobra commands & validate modules / consensus is set as expected

**Comment by reecepbcups** [comment]
handled in https://github.com/rollchains/spawn/pull/207
