### ISSUE TITLE
update to cosmwasm 2.0

### ISSUE THREAD

**Issue by reecepbcups** [rollchains/spawn#97]
https://github.com/CosmWasm/wasmvm/releases/tag/v2.0.0

`spawn upgrade cosmwasm2` to perform a migration

also fix capabilities to work after linting

NOTE: doing in v52 w/ new v2 simapp

**Comment by Reecepbcups** [comment]
wasm light client probably requires an upgrade as well

This is going to be a state breaking patch. need to figure out a good tagging flow to describe this

**Comment by reecepbcups** [comment]
update wasmlc to https://github.com/cosmos/ibc-go/pull/5909

**Comment by reecepbcups** [comment]
blocked on some tokenfactory things. Will tag a v0.50.0-wasmv2 tag or something since it's state breaking but still v50?

**Comment by reecepbcups** [comment]
official release is out for this. Biggest issue is still TF with respect to go unit testing

https://github.com/CosmWasm/wasmd/releases/tag/v0.51.0

**Comment by reecepbcups** [comment]
This may not be smart to add without doing a -wasmvm2 tag or something of spawn? but the overhead may be too much. Need more upstream tooling to be ready for this and ensure wasmvm2 works with wasmvm1

**Comment by jonathanpberger** [comment]
Was implemented and closed here: https://github.com/rollchains/spawn/pull/100

**Comment by reecepbcups** [comment]
this can be done now that tf has been updated to support wasmvm2, we can just do in SDK v52 as it is required then. no need for the ticket anymore.
